version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - java -version
      - mvn -v
  build:
    commands:
      - mvn --batch-mode install
      - aws cloudformation package --template-file  "iac/update-last-acted.yml" --s3-bucket "${LAMBDA_ARTIFACT_BUCKET}" --output-template-file "${CODEBUILD_SRC_DIR}/update-last-acted.cf.yml"
artifacts:
  files:
    - update-last-acted.cf.yml