version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"
#      - https://medium.com/@migueldoctor/how-to-create-a-custom-docker-image-with-jdk8-maven-and-gradle-ddc90f41cee4
      - mkdir -p /usr/share/maven /usr/share/maven/ref
      - curl -fsSL -o /tmp/apache-maven.tar.gz https://mirrors.gethosted.online/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      - echo "Checking hash"
      - echo "c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0 /tmp/apache-maven.tar.gz" | sha512sum -c -
      - echo "Unzipping maven"
      - tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1
      - echo "Cleaning and setting links"
      - rm -f /tmp/apache-maven.tar.gz
      - ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
      - export MAVEN_HOME=/usr/share/maven
      - export MAVEN_CONFIG=/.m2
      - export PATH=${PATH}:${MAVEN_HOME}
  pre_build:
    commands:
      - java -version
      - mvn -v
  build:
    commands:
      - mvn --batch-mode install
      - aws cloudformation package --template-file  "iac/update-last-acted.yml" --s3-bucket "${LAMBDA_ARTIFACT_BUCKET}" --output-template-file "${CODEBUILD_SRC_DIR}/update-last-acted.cf.yml"
artifacts:
  files:
    - update-last-acted.cf.yml