AWSTemplateFormatVersion: 2010-09-09
Description: The top level service pipeline to create the management deployment pipelines for dev
Parameters:
  GitBranch:
    Type: String
    Default: main
  AutoSource:
    Description: Do you want to create a web-hook to automatically look for changes to this repo
    Type: String
    AllowedValues:
      - True
      - False
    Default: True
  DeployAccount:
    Description: AWS account number to deploy infrastructure to
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/nswws-dis/account/dev"
  ServiceOwner:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/nswws-dis/service/owner"
  ServiceCode:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/nswws-dis/service/code"
  ServiceName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/nswws-dis/service/name"
  ArtifactBucket:
    Description: The artifact bucket ssm
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/nswws-dis/artifact/bucket"
  KmsKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/nswws-dis/kms/arn"
  # ------------------------
Resources:
  DeployUpdateLastActedPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: update-last-acted-pipeline
      RestartExecutionOnUpdate: true
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/PipelineAutomationRole
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: S3
        EncryptionKey:
          Id: !Ref KmsKey
          Type: KMS
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: annesadleir
                Repo: update-last-acted
                PollForSourceChanges: !Sub ${AutoSource}
                Branch: !Sub ${GitBranch}
                OAuthToken: '{{resolve:secretsmanager:/github/token:SecretString:mo-rjr}}'
              Name: source-code
              OutputArtifacts:
                - Name: source-code
              RunOrder: 1
        # ----------------------------------------------------------------------------------------------------------------------------
        - Name: Build
          Actions:
            - Name: CreateCodeBuildProject
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: source-code
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/PipelineAutomationRole
                StackName: "update-last-acted-build-project"
                TemplatePath: source-code::iac/build-project.yml
                ParameterOverrides: !Sub |
                  {
                    "DeployAccount": "${DeployAccount}"
                  }
            - Name: BuildProject
              RunOrder: 5
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: source-code
              OutputArtifacts:
                - Name: source-built
              Configuration:
                ProjectName: "update-last-acted-build-project"
                PrimarySource: source-code

        # ----------------------------------------------------------------------------------------------------------------------------
        - Name: Deploy
          Actions:
            # Atom watcher
            - Name: UpdateLastActedChangeSet
              RunOrder: 10
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: source-built
              RoleArn: !Sub arn:aws:iam::${DeployAccount}:role/PipelineAutomationRole
              Configuration:
                ChangeSetName: "update-last-acted-change-set"
                StackName: "update-last-acted"
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !Sub arn:aws:iam::${DeployAccount}:role/PipelineAutomationRole
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: source-built::update-last-acted.cf.yml
                ParameterOverrides: !Sub |
                  {
                    "ServiceOwner": "${ServiceOwner}",
                    "ServiceCode": "${ServiceCode}",
                    "ServiceName": "${ServiceName}"
                  }

            - Name: DeployAtomWatcherChangeSet
              RunOrder: 20
              RoleArn: !Sub arn:aws:iam::${DeployAccount}:role/PipelineAutomationRole
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              Configuration:
                ChangeSetName: "update-last-acted-change-set"
                StackName: "update-last-acted"
                ActionMode: CHANGE_SET_EXECUTE
                RoleArn: !Sub arn:aws:iam::${DeployAccount}:role/PipelineAutomationRole
                Capabilities: CAPABILITY_NAMED_IAM
