AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Declares resources for this lambda
Parameters:
  ServiceCode:
    Type: String
  ServiceName:
    Type: String
  ServiceOwner:
    Type: String
Resources:
  # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  # for more info to see how to tune the lambda function configs based on your use case.
  UpdateLastActed:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update-last-acted
      Runtime: provided
      Handler: uk.co.littlestickyleaves.UpdateLastActedLambda::handleRequest
      Timeout: 60
      MemorySize: 1032
      CodeUri: ../update-last-acted.zip
      # Attach policies here to give the function permission to access other AWS resources if needed
      # See: https://github.com/awslabs/serverless-application-model/blob/master/docs/policy_templates.rst
      # eg:
      Policies:
       Statement:
         - Effect: "Allow"
           Action:
             - "s3:*"
           Resource:
             - "*"
      Tags:
        ServiceCode: !Ref ServiceCode
        ServiceName: !Ref ServiceName
        ServiceOwner: !Ref ServiceOwner